all: h.test h2.test n2.test si.test

clean: 
	rm -f *.test report.csv

h.test: 
	cd h && ./run_test.py

h2.test:
	cd h2 && ./run_test.py 

n2.test:
	cd n2 && ./run_test.py

si.test:
	cd si && ./run_test.py
