#!/usr/bin/env python
from __future__ import print_function
import subprocess
import json
import sys
import math

sys.path.append("../")
from qwtest import *
print("""###########################################
Checking the linear method for the H2 molecule. 
This tests the LINEAR method, the Jastrow factor, analytic parameter derivatives..
The reference is a previous QWalk run. 
################################################""")

try:
  subprocess.check_output(['rm','qw.linear.o','qw.linear.config'])
except:
  pass
subprocess.check_output([QW,'qw.linear'])


ref_data=[-1.068309651,0.0009113787988]

run_data=[0.0,0.0]
with open("qw.linear.o") as f:
  for line in f:
    if 'current energy' in line:
      spl=line.split()
      run_data[0]=float(spl[4])
      run_data[1]=float(spl[6])

print("Reference data:",ref_data)
print("This run:",run_data)
#I added a factor of 2 fudge factor to account for differences in optimization.
if check_errorbars(ref_data[0],run_data[0],2.*math.sqrt(ref_data[1]**2+run_data[1]**2)):
  print("PASSED")
  sys.exit(0)
print("FAILED")
sys.exit(1)
