#!/usr/bin/env python
from __future__ import print_function
import subprocess
import json
import sys

sys.path.append("../")
from qwtest import *

print("""###########################################
Checking VMC and Slater determinant for the stretched N2 dimer.
This tests the orbital evaluation routine, the VMC method, ECPs, and multiple determinants.
The reference is the CI result from GAMESS.
################################################""")

try:
  subprocess.check_output(['rm','qw.ci.log','qw.ci.config'])
except:
  pass
subprocess.check_output([QW,'qw.ci'])
json_str=subprocess.check_output([GOS,'-json','qw.ci.log'])

dat=json.loads(json_str)

ref_data={'total_energy': -19.3080264611,
          'kinetic':12.2497549662,
          }


success={}
for k in ref_data.keys():
  success[k]=check_errorbars(ref_data[k],
                  dat['properties'][k]['value'][0],
                  dat['properties'][k]['error'][0])
for k in ref_data.keys():
  success[k+'sane']=check_sane(ref_data[k],
                  dat['properties'][k]['value'][0],
                  dat['properties'][k]['error'][0])

allsuc=[]
for k,v in success.items():
  allsuc.append(v)
  print(k,v)
if False in allsuc:
  exit(1)

